## SQL QUESTIONS

use org;

show tables;

## WORKER TABLE
select* from worker;

## Bonus TABLE
select* from bonus;

## TITLE TABLE
select* from title;

-- SQL QUERIES

/*
  1. WRITE AN SQL QUERY TO FETCH "FIRST_NAME: FROM WORKER TABLE USING 
  THE ALIAS NAME AS <WORKER_NAME>."
*/
SELECT FIRST_NAME AS WORKER_NAME FROM WORKER;


/*
	2. WRITE AN SQL QUERY TO FECTH "FIRST_NAME" FROM WORKER 
    TABLE IN UPPER CASE.
*/
SELECT UPPER(FIRST_NAME) FROM Worker;

/*
	3. WRITE AN SQL QUERY TO FETCH
    UNIQUE VALUES OF DEPARTMENT FROM WORKER TABLE
*/
SELECT DISTINCT Department from Worker;

/*
	4. WRITE AN SQL QUERY TO PRINT THE FIRST THREE CHARACTERS OF
    FIRST_NAME FROM WORKER TABLE.
*/
SELECT substring(FIRST_NAME, 1,3) from Worker;

/*
	5. WRITE AN SQL QUERY TO FIND THE POSITION OF THE ALPHABET
	('a') in the first name column 'Amitabh' from Worket table.
*/
SELECT instr(FIRST_NAME, BINARY'a') 
FROM Worker
WHERE FIRST_NAME = 'Amitabh';

/*
	6. WRITE AN SQL QUERY TO PRINT FIRST_NAME FROM 
    WORKER TABLE AFTER REMOVING WHITE SPACES 
    FROM THE RIGHT SIDE.
*/
SELECT RTRIM(FIRST_NAME) 
FROM Worker;

/*
	7. WRITE AN SQL QUERY TO PRINT THE 
    DEPARTMENT FROM WORKER TABLE AFTER
    REMOVING WHITE SPACES FROM THE LEFT SIDE.
*/
SELECT ltrim(DEPARTMENT) from Worker;

/* 
	8. WRITE AN SQL QUERY THAT FETCHES THE UNIQUE
    VALUES OF DEPARTMENT FROM WORKER TABLE
    AND PRINTS ITS LENGTH.
*/
SELECT DISTINCT length(DEPARTMENT) FROM Worker;

/*
	9.WRITE AN SQL QUERY TO PRINT THE FIRST_NAME
    FROM WORKER TABLE AFTER REPLACING 'a' WITH 'A'
*/
SELECT REPLACE(FIRST_NAME, 'a', 'A') FROM Worker;

/*
	10. WRITE AN SQL QUERY TO PRINT THE FIRST_NAME AND 
    LAST_NAME FROM WORKER TABLE INTO A SINGLE COLUMN
    COMPLETE_NAME. A SPACE CHAR SHOULD BE SEPERATE THEM.
*/
SELECT CONCAT(FIRST_NAME, ' ',LAST_NAME) AS 'COMPLETE_NAME' 
FROM Worker;

/*
	11. WRITE AN SQL QUERY TO PRINT ALL WORKER 
    DETAILS FROM THE WORKER TABLE ORDER BY FIRST_NAME ASCENDING.
*/
SELECT* FROM Worker
ORDER BY FIRST_NAME asc;

/*
	12. WRITE AN SQL QUERY TO PRINT ALL WORKER DETAILS FROM THE
    WORKER TABLE ORDER BY FIRST_NAME ASCENDING AND 
    DEPARTMENT DESCENDING.
*/
SELECT* FROM WORKER
ORDER BY FIRST_NAME ASC, DEPARTMENT DESC;

/*
	13. WRITE AN SQL QUERY TO PRINT DETAILS
    FROM WORKERS WITH FIRST_NAME AS "VIPUL" AND "SATISH"
    FROM WORKER TABLE.
*/
SELECT* FROM Worker
WHERE FIRST_NAME IN ('Vipul', 'Satish');

/*
	14. WRITE AN SQL QUERY TO PRINT
    DETAILS OF WORKERS EXCLUDING FIRST NAMES,
    "Vipul" and "Satish" FROM WORKER TABLE.
*/
SELECT* FROM WORKER 
WHERE FIRST_NAME NOT IN ('Vipul', 'Satish');

/*
	15.WRITE AN SQL QUERY TO PRINT DETAILS OF 
    WORKERS WITH DEPARTMENT NAME AS "ADMIN".
*/
SELECT* 
FROM WORKER 
WHERE DEPARTMENT = "Admin";

/*
	16. WRITE AN SQL QUERY TO PRINT DETAILS OF 
    THE WORKERS WHOSE FIRST_NAME CONTAINS 'a'
*/
SELECT * FROM Worker
WHERE FIRST_NAME LIKE '%a%';

/*
	17. WRITE AN SQL QUERY TO PRINT 
    DETAILS OF THE WORKERS
    WHOSE FIRST_NAME ENDS WITH 'a'
*/
SELECT* FROM WORKER
WHERE FIRST_NAME LIKE '%a';

/*
	18, WRITE AN SQL QUERY TO PRINT 
    DETAILS OF THE WORKERS
    WHOSE SALARY LIES BETWEEN 100000 AND 500000
*/
SELECT* FROM WORKER
WHERE SALARY BETWEEN 100000 AND 500000; 